export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SEEKER_PROFILE = "SET_SEEKER_PROFILE";
export const SET_SEEKER_PROFILES = "SET_SEEKER_PROFILES";
export const SET_EMPLOYER_PROFILE = "SET_EMPLOYER_PROFILE";
